export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_RESET_ITEM = 'CART_RESET_ITEM'

export const CART_SIDEBAR_ACTIVE = 'CART_SIDEBAR_ACTIVE'
export const CART_SIDEBAR_HIDE = 'CART_SIDEBAR_HIDE'

export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
